@startuml
  class Snapshot {
    + id : UUID
    + aggregateId : String
    + aggregateType : String
    + data : ByteArray
    + metaData : ByteArray
    + version : Int
    + timeStamp : LocalDateTime
  }
@enduml
