{
 "title": "Event Dashboard",
 "time": { "from": "2025-11-25T21:33:04.633Z", "to": "2025-11-25T21:53:04.633Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Spring Events Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(events_spring_published_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Consumed Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_spring_consumed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Spring Events Published",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(events_spring_published_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Published Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_spring_published_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RabbitMQ Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(events_rabbitmq_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RabbitMQ Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_rabbitmq_received_total", "legendFormat": "__auto" }
   ]
  }
 ]
}