{
 "title": "Parking Operation Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Vehicles in Parking Lot",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vehicles_in_parking_lot", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Vehciles Parked Correct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(vehicles_correct_parked_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vehicles Parked Wrong",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(vehicles_wrong_parked_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}