{
 "title": "Technical Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{job}} CPU" }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{area}} - {{id}}"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (uri)(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}